# Generated by Django 4.0 on 2021-12-31 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_author_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPenName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(max_length=255)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.author')),
            ],
        ),
    ]
